# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: jgeddes@turing.ac.uk
full_name: James Geddes
license: MIT
min_python_version: '3.13'
org: alan-turing-institute
project_name: rcpond
project_short_description: A tool to partly automate RCP requests
python_name: rcpond
typing: loose
url: https://github.com/alan-turing-institute/rcpond
