site_name: RCPond
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: numpy
            show_submodules: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition