"""Parse ServiceNow ticket HTML export files.

Provides two public functions:

- ``extract_key_facts(filename)``: Parse a ServiceNow ticket HTML file and
  return a dict of extracted fields.
- ``parse_ticket_html(filename)``: Parse a ServiceNow ticket HTML file and
  return a ``FullTicket`` instance.

The HTML files are generated by the ServiceNow export endpoint::

    /x_tati_resmgt_research.do?sys_id={sys_id}&sysparm_view=Export_to_pdf&...

Return types
------------
``extract_key_facts`` returns a ``dict[str, str | pd.DataFrame | None]``.
String fields are ``None`` when the corresponding element is absent from the HTML.
The ``"activities"`` key always holds a ``pd.DataFrame`` (empty if no activities
are found).

``parse_ticket_html`` returns a ``FullTicket``.

No configuration is required.
"""

from pathlib import Path

import pandas as pd
from bs4 import BeautifulSoup, Tag

from rcpond.servicenow import FullTicket, Ticket

_SHORT_DESCRIPTION = "Request access to HPC and cloud computing facilities"

## ---- Internal helpers ----


def _input_value(soup: BeautifulSoup, input_id: str) -> str | None:
    """Return the ``value`` attribute of the first ``<input id=...>`` found, or ``None``."""
    tag = soup.find("input", {"id": input_id})
    if not isinstance(tag, Tag):
        return None
    val = tag.get("value")
    return val if isinstance(val, str) else None


def _extract_sys_id(soup: BeautifulSoup) -> str | None:
    # Extract the record's own sys_id from the hidden sys_uniqueValue field
    return _input_value(soup, "sys_uniqueValue")


def _extract_ticket_number(soup: BeautifulSoup) -> str | None:
    # Extract ticket number
    return _input_value(soup, "sys_readonly.x_tati_resmgt_research.number")


def _extract_assigned_to(soup: BeautifulSoup) -> dict[str, str]:
    # Extract the assigned_to field as a {value, display_value} dict matching
    # the format returned by ServiceNow.get_assignee()
    return {
        "display_value": _input_value(soup, "x_tati_resmgt_research.assigned_to_label") or "",
        "value": _input_value(soup, "x_tati_resmgt_research.assigned_to") or "",
    }


def _extract_state(soup: BeautifulSoup) -> str | None:
    # Extract state
    return _input_value(soup, "sys_readonly.x_tati_resmgt_research.state")


def _extract_activities_as_table(soup: BeautifulSoup) -> pd.DataFrame:
    """Extract all activities from the activity table as a DataFrame.

    Parameters
    ----------
    soup : BeautifulSoup
        Parsed HTML document.

    Returns
    -------
    pd.DataFrame
        Columns: date, user, field_name, field_label, value, previous_value, text.
        Empty DataFrame (with those columns) if no activity table is found.
    """
    rows = []

    # Find the activity detail table
    activity_table = soup.find("table", {"id": lambda x: x and x.startswith("activity_detail.")})

    if not isinstance(activity_table, Tag):
        return pd.DataFrame(
            columns=[
                "date",
                "user",
                "field_name",
                "field_label",
                "value",
                "previous_value",
                "text",
            ]
        )

    # Find all activity header rows
    activity_headers = activity_table.find_all("tr", class_="activity_header")

    for header in activity_headers:
        # Extract date
        date_span = header.find("span", class_="activity_date")
        date = date_span.get_text(strip=True) if date_span else None

        # Extract user
        user_span = header.find("span", class_="user")
        user = user_span.get_text(strip=True) if user_span else None

        # Find the corresponding data row
        data_row = header.find_next_sibling("tr", class_="activity_data")
        if data_row:
            field_divs = data_row.find_all("div", class_="activity_field")

            for div in field_divs:
                field_name = div.get("name")
                field_label = div.get("label")

                # Check if it's a comment or work note (has text block)
                text_block = div.find("span", class_="sn-widget-printer-friendly-textblock")
                if text_block:
                    # Comment or work note
                    rows.append(
                        {
                            "date": date,
                            "user": user,
                            "field_name": field_name,
                            "field_label": field_label,
                            "value": None,
                            "previous_value": None,
                            "text": text_block.get_text(strip=True),
                        }
                    )
                else:
                    # Field change
                    value_span = div.find("span", class_="activity_value")
                    was_value_span = div.find("span", class_="activity_was_value")

                    rows.append(
                        {
                            "date": date,
                            "user": user,
                            "field_name": field_name,
                            "field_label": field_label,
                            "value": (value_span.get_text(strip=True) if value_span else None),
                            "previous_value": (was_value_span.get_text(strip=True) if was_value_span else None),
                            "text": None,
                        }
                    )

    return pd.DataFrame(rows)


def _extract_displayed_activity_count(activities: pd.DataFrame) -> int:
    """Return the count of activities as displayed in ServiceNow.

    This value does NOT include activities related to the initial ticket creation.

    Parameters
    ----------
    activities : pd.DataFrame
        Output of ``_extract_activities_as_table``.

    Returns
    -------
    int
        Number of displayed activity entries.
    """
    creation_date_time = activities["date"].min()
    displayed_activities = activities[activities["date"] != creation_date_time]
    return len(displayed_activities)


def _extract_comments(activities: pd.DataFrame) -> pd.DataFrame:
    return activities[activities["field_name"].isin(("comments", "work_notes"))]


def _extract_comment_count(activities: pd.DataFrame) -> int:
    return len(_extract_comments(activities))


def _extract_data_sensitivity(soup: BeautifulSoup) -> str | None:
    return _extract_question_answer_pair_table(soup, "data sensitivity")


def _extract_platform_choice(soup: BeautifulSoup) -> str | None:
    return _extract_question_answer_pair_table(soup, "which service")


def _extract_research_area_or_programme(soup: BeautifulSoup) -> str | None:
    answer = _extract_question_answer_pair_table(soup, "research area/programme")
    if not answer or answer.lower() == "other":
        answer = _extract_question_answer_pair_table(soup, "If other, please specify")

    return answer


def _extract_category(soup: BeautifulSoup) -> str:
    category = soup.find_all("input", {"id": lambda x: x and x.endswith("u_category_label")})
    if len(category) != 1:
        err_msg = f"Expected exactly one 'u_category_label' item, found {len(category)} items"
        raise ValueError(err_msg)

    return category[0].get("value")


def _extract_sub_category(soup: BeautifulSoup) -> str:
    sub_category = soup.find_all("input", {"id": lambda x: x and x.endswith("u_sub_category_label")})
    if len(sub_category) != 1:
        err_msg = f"Expected exactly one 'u_sub_category_label' item, found {len(sub_category)} items"
        raise ValueError(err_msg)

    return sub_category[0].get("value")


def _extract_question_answer_pair_table(
    soup: BeautifulSoup, question: str, starting_point: str | None = None
) -> str | None:
    """Extract an answer from a question-answer pair table.

    Some fields are stored as question-answer pairs in a 1xN table: the question
    is the first cell, the answer is the last cell. This function finds the answer
    given the question text.

    Parameters
    ----------
    soup : BeautifulSoup
        Parsed HTML document (or sub-tree).
    question : str
        The question text to search for (case-insensitive).
    starting_point : str | None
        Optional string to narrow the search area. Useful when the question
        appears multiple times; the next occurrence after this string is used.

    Returns
    -------
    str | None
        The answer text, or ``None`` if not found.
    """
    label_tag = None
    if not starting_point:
        label_tag = soup.find("label", string=lambda s: s and question.lower() in s.strip().lower())
    else:
        # Make sure that we are not searching inside a script tag
        starting_tag = soup.find(
            string=lambda s: s
            and starting_point.lower() in s.strip().lower()
            and getattr(s, "parent", None) is not None
            and s.find_parent("script") is None
        )
        if starting_tag:
            # We are looking for the question after the starting point, so limit search to that table
            parent_table = starting_tag.find_parent("table")
            if parent_table:
                label_tag = parent_table.find("label", string=lambda s: s and question.lower() in s.strip().lower())

    if label_tag:
        # Find the table row containing the label, then get the next row in the same table
        tr = label_tag.find_parent("tr")
        if not tr:
            td = label_tag.find_parent("td")
            tr = td.find_parent("tr") if td else None

        if tr:
            current = tr.find_next_sibling("tr")
            last_tr = None
            while current is not None:
                last_tr = current
                current = current.find_next_sibling("tr")
            next_tr = last_tr
            if next_tr:
                return next_tr.get_text(" ", strip=True)

    return None


## ---- Public API ----


def extract_key_facts(filename: Path) -> dict:
    """Extract ticket fields from a ServiceNow HTML export file.

    Parameters
    ----------
    filename : Path
        Path to the HTML file.

    Returns
    -------
    dict[str, str | pd.DataFrame | None]
        Extracted fields. String values are ``None`` when the corresponding
        HTML element is absent. ``"activities"`` is always a ``pd.DataFrame``.
    """
    soup = BeautifulSoup(filename.read_text(), "html.parser")

    activities = _extract_activities_as_table(soup)

    comments = _extract_comments(activities)
    work_notes = "\n\n".join(comments["text"].dropna())

    def _q(question: str, starting_point: str | None = None) -> str:
        return _extract_question_answer_pair_table(soup, question, starting_point) or ""

    return {
        ## Internal keys (not FullTicket fields)
        "sys_id": _extract_sys_id(soup),
        "ticket_number": _extract_ticket_number(soup),
        "assigned_to": _extract_assigned_to(soup),
        "state": _extract_state(soup),
        "category": _extract_category(soup),
        "sub_category": _extract_sub_category(soup),
        "activity_count": str(len(activities)),
        "comment_count": str(_extract_comment_count(activities)),
        "activities": activities,
        ## FullTicket fields — keys match FullTicket field names exactly
        "work_notes": work_notes,
        "which_service": _extract_platform_choice(soup) or "",
        "requested_for": _q("requested for", "Variables"),
        "project_title": _q("project title"),
        "research_area_programme": _extract_research_area_or_programme(soup) or "",
        "pi_supervisor_name": _q("PI/Supervisor name"),
        "pi_supervisor_email": _q("PI/Supervisor email"),
        "subscription_type": _q("Subscription type"),
        "which_finance_code": _q("Which finance code"),
        "pmu_contact_email": _q("PMU Contact email"),
        "credits_requested": _q("Credits requested"),
        "which_facility": _q("Which facility"),
        "if_other_please_specify": "",  ## handled by fallback logic in _extract_research_area_or_programme
        "if_other_please_specify_facility": "",
        "cpu_hours_required": _q("CPU hours required?"),
        "gpu_hours_required": _q("GPU hours required?"),
        "new_or_existing_allocation": _q("New or existing allocation"),
        "azure_subscription_id_or_hpc_group_project_id": _q("Azure subscription ID or HPC Group/Project ID"),
        "start_date": _q("Start date"),
        "end_date": _q("End date"),
        "data_sensitivity": _q("Data sensitivity"),
        "platform_justification": _q("Platform justification"),
        "research_justification": _q("Research justification"),
        "computational_requirements": _q("Computational requirements"),
        "users_who_require_access_names_and_emails": _q("Users who require access (names and emails)"),
        "cost_compute_time_breakdown": _q("Cost/compute time breakdown"),
    }


def parse_ticket_html(filename: Path) -> FullTicket:
    """Parse a ServiceNow ticket HTML export file and return a ``FullTicket``.

    Parameters
    ----------
    filename : Path
        Path to the HTML file.

    Returns
    -------
    FullTicket
    """
    facts = extract_key_facts(filename)
    activities = facts["activities"]

    ## Use the earliest activity date as a best-effort stand-in for opened_at
    opened_at = ""
    if not activities.empty and activities["date"].notna().any():
        opened_at = activities["date"].dropna().min() or ""

    ticket = Ticket(
        sys_id=facts.get("sys_id") or filename.stem,
        number=facts.get("ticket_number") or "",
        opened_at=opened_at,
        requested_for=facts.get("requested_for") or "",
        u_category=facts.get("category") or "",
        u_sub_category=facts.get("sub_category") or "",
        short_description=_SHORT_DESCRIPTION,
    )
    return FullTicket.from_Ticket(
        ticket,
        work_notes=facts["work_notes"],
        project_title=facts["project_title"],
        research_area_programme=facts["research_area_programme"],
        if_other_please_specify=facts["if_other_please_specify"],
        pi_supervisor_name=facts["pi_supervisor_name"],
        pi_supervisor_email=facts["pi_supervisor_email"],
        which_service=facts["which_service"],
        subscription_type=facts["subscription_type"],
        which_finance_code=facts["which_finance_code"],
        pmu_contact_email=facts["pmu_contact_email"],
        credits_requested=facts["credits_requested"],
        which_facility=facts["which_facility"],
        if_other_please_specify_facility=facts["if_other_please_specify_facility"],
        cpu_hours_required=facts["cpu_hours_required"],
        gpu_hours_required=facts["gpu_hours_required"],
        new_or_existing_allocation=facts["new_or_existing_allocation"],
        azure_subscription_id_or_hpc_group_project_id=facts["azure_subscription_id_or_hpc_group_project_id"],
        start_date=facts["start_date"],
        end_date=facts["end_date"],
        data_sensitivity=facts["data_sensitivity"],
        platform_justification=facts["platform_justification"],
        research_justification=facts["research_justification"],
        computational_requirements=facts["computational_requirements"],
        users_who_require_access_names_and_emails=facts["users_who_require_access_names_and_emails"],
        cost_compute_time_breakdown=facts["cost_compute_time_breakdown"],
    )
