name: Test Installer

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test installation with python ${{ matrix.python-version }}
        run: uv tool install git+ssh://git@github.com/alan-turing-institute/rcpond.git
      - name: Verify the tool can be run
        run: rcpond --help | grep "Show this message and exit"
